#!/usr/bin/env python
# coding: utf-8

# Part of the JSON-based-chanarchiver by Lawrence Wu, 2012/04/04
# Originally from https://github.com/socketubs/4chandownloader
# Rewritten to save in seperate images folder, download plain HTML, modularization, comments, and code cleanup

#
# Initial release Nov. 5, 2009
# v6 release Jan. 20, 2009
# http://cal.freeshell.org
#
# Refactor, update and Python package
# by Socketubs (http://socketubs.net/)
# 09-08-12
#

import os
import time
import json
from docopt import docopt
import requests
import errno

doc = """4chandownloader.py, uses 4chan API to download thread images and/or 
thumbnails, along with thread HTML and JSON.

Usage:
  4chandownloader.py <url> <path> [--delay=<int>] [--thumbs] [--thumbsonly]
  4chandownloader.py -h | --help
  4chandownloader.py -v | --version

Options:
  --thumbs            Download thumbnails
  --thumbsonly        Download thumbnails, no images
  --delay=<int>       Delay between thread checks [default: 20]
  -h --help           Show help
  -v --version        Show version
"""

# Create paths if they don't exist 
# replace with `os.makedirs(path,exist_ok=True)` in python3
def make_sure_path_exists(path):
    try:
        os.makedirs(path)
    except OSError as exception:
        if exception.errno != errno.EEXIST:
            raise

# Download any file using requests
def downloadFile(file_name, dst, file_url):
    # Destination of downloaded file
    file_dst = os.path.join(dst, file_name)
    
    # If the file doesn't exist, download it
    if not os.path.exists(file_dst):
	print('%s downloading...' % file_name)
	i = requests.get(file_url)
	if i.status_code == 404:
	    print(' | Failed, try later (%s)' % file_url)
	else:
	    open(file_dst, 'w').write(i.content)
    else:
	print('%s already downloaded' % file_name)

def main(args):
    # Copy data from arguments
    thread = args.get('<url>').split('/')[5]
    board  = args.get('<url>').split('/')[3]
    path   = args.get('<path>')
    thumbs = args.get('--thumbs', False)
    thumbsonly = args.get('--thumbsonly', False)
    delay  = args.get('--delay')

    # paths to file destination folders
    # path - folder/board/thread/
    # image path - folder/board/thread/images/<image-timestamp>.<ext>
    # thumbnails path - folder/board/thread/thumbs/<image-timestamp>s.jpg
    dst = os.path.join(path, board, thread)
    dst_images = os.path.join(dst, 'images')
    dst_thumbs = os.path.join(dst, 'thumbs')

    # Create paths if they don't exist
    # Don't create images folder if user only wants thumbnails
    # Create thumbs directory if thumbnails are needed
    make_sure_path_exists(dst)
    if not thumbsonly:
      make_sure_path_exists(dst_images)
    if thumbs or thumbsonly:
      make_sure_path_exists(dst_thumbs)

    # paths to 4chan URLs (with regex!)
    fourchan_api_url = 'https://api.4chan.org/%s/res/%s.json'
    fourchan_images_url = 'https://images.4chan.org/%s/src/%s'
    fourchan_thumbs_url = 'https://thumbs.4chan.org/%s/thumb/%s'
    fourchan_boards_url = 'http://boards.4chan.org/%s/res/%s'

    # Begin file dump loop
    while 1:
	print(' :: Board: %s' % board)
	print(' :: Thread: %s' % thread)
	
	# Grab thread JSON from 4chan API
	r = requests.get(fourchan_api_url % (board, thread))
	
	for post in r.json['posts']:
	    if post.get('filename', False):
		# If file is deleted, move on
		if post.get('filedeleted', False):
		    continue
		
		# Download images, if not only downloading thumbnails
		if not thumbsonly:
		    # Set filenames and paths for images
		    image_name = '%s%s' % (post['tim'], post['ext'])
		    image_url  = fourchan_images_url % (board, image_name)
		    downloadFile(image_name, dst_images, image_url)

		# Only download thumbnails if user specifies to do so
		if thumbs or thumbsonly:
		    # Set filenames and paths for thumbnails
		    thumb_name = '%ss.jpg' % post['tim']
		    thumb_url  = fourchan_thumbs_url % (board, thumb_name)
		    downloadFile(thumb_name, dst_thumbs, thumb_url)

	#
	# Dumps thread in raw HTML format to `thread.html` file
	# (FUTURE) we need to convert all links
	# 
	# Filename: ./board/thread/<thread-id>.html
	# 
	html_name = '%s.html' % thread
	html_url = fourchan_boards_url % (board, thread)
	downloadFile(html_name, dst, html_url)
	
	# 
	# Dumps thread in JSON format to `threadid.json` file
	# 
	# Filename: ./board/thread/<thread-id>.json
	# 
	jsonPath = os.path.join(dst, thread + ".json")
	json.dump(r.json, open(jsonPath, 'w'))

	# Wait to execute code again
	print("Waiting %s seconds before retrying" % delay)
	time.sleep(int(delay))

if __name__ == '__main__':
  args = docopt(doc, version=0.3)
  main(args)
